# 数据库连接设置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/studentsdormitory?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root


thymeleaf:
  prefix: classpath:/templates/
  mode: HTML5
  cache: false
  encoding: UTF-8

# mybatis 配置
mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:/mybatis/mapper/*.xml


# 设置全局日期格式,如果设置这个格式,则代码中@DateTimeFormat(pattern = "dd/MM/yyyy") 无效!!
mvc:
  format:
    date: yyyy-MM-dd
server:
  port: 8888
  servlet:
    encoding:
      charset: utf-8


#
logging:
  level:
    com.example.demo.mapper: debug
